INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (1,'Afghanistan','Afghan','AF','+93','','','',1),
	 (2,'Albania','Albanian','AL','+355','ALL','Albanian lek','L',1),
	 (3,'Algeria','Algerian','DZ','+213','DZD','Algerian dinar','د.ج',1),
	 (4,'American Samoa','American Samoan','AS','+1684','USD','United State Dollar','$',1),
	 (5,'Andorra','Andorran','AD','+376','EUR','Euro','€',1),
	 (6,'Angola','Angolan','AO','+244','AOA','Angolan kwanza','Kz',1),
	 (7,'Anguilla','Anguillian','AI','+1264','XCD','East Caribbean dollar','$',1),
	 (8,'Antarctica','Antarctica','AQ','+672','','','',1),
	 (9,'Antigua And Barbuda','Antiguan, Barbudan','AG','+1268','XCD','East Caribbean dollar','$',1),
	 (10,'Argentina','Argentinean','AR','+54','ARS','Argentine peso','$',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (11,'Armenia','Armenian','AM','+374','AMD','Armenian dram','',1),
	 (12,'Aruba','Aruban','AW','+297','AWG','Aruban florin','ƒ',1),
	 (13,'Australia','Australian','AU','+61','AUD','Australian dollar','$',1),
	 (14,'Austria','Austrian','AT','+43','EUR','Euro','€',1),
	 (15,'Azerbaijan','Azerbaijani','AZ','994','AZN','Azerbaijani manat','',1),
	 (16,'Bahamas The','Bahamian','BS','+1','','','',1),
	 (17,'Bahrain','Bahraini','BH','+973','BHD','Bahraini dinar','.د.ب',1),
	 (18,'Bangladesh','Bangladeshi','BD','+880','BDT','Bangladeshi taka','৳',1),
	 (19,'Barbados','Barbadian','BB','+1246','BBD','Barbadian dollar','$',1),
	 (20,'Belarus','Belarusian','BY','+375','BYN','New Belarusian ruble','Br',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (21,'Belgium','Belgian','BE','+32','EUR','Euro','€',1),
	 (22,'Belize','Belizean','BZ','+501','BZD','Belize dollar','$',1),
	 (23,'Benin','Beninese','BJ','+229','XOF','West African CFA franc','Fr',1),
	 (24,'Bermuda','Bermudian','BM','+1441','BMD','Bermudian dollar','$',1),
	 (25,'Bhutan','Bhutanese','BT','+975','BTN','Bhutanese ngultrum','Nu.',1),
	 (26,'Bolivia','Bolivian','BO','+591','BOB','Bolivian boliviano','Bs.',1),
	 (27,'Bosnia and Herzegovina','Bosnian, Herzegovinian','BA','+387','','','',1),
	 (28,'Botswana','Motswana','BW','+267','BWP','Botswana pula','P',1),
	 (29,'Bouvet Island','','BV','+55','','','',1),
	 (30,'Brazil','Brazilian','BR','+55','BRL','Brazilian real','R$',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (31,'British Indian Ocean Territory','Indian','IO','+246','USD','United States dollar','$',1),
	 (32,'Brunei','Bruneian','BN','+673','','','',1),
	 (33,'Bulgaria','Bulgarian','BG','+359','BGN','Bulgarian lev','лв',1),
	 (34,'Burkina Faso','Burkinabe','BF','+226','XOF','West African CFA franc','Fr',1),
	 (35,'Burundi','Burundian','BI','+257','BIF','Burundian franc','Fr',1),
	 (36,'Cambodia','Cambodian','KH','+855','KHR','Cambodian riel','៛',1),
	 (37,'Cameroon','Cameroonian','CM','+237','XAF','Central African CFA franc','Fr',1),
	 (38,'Canada','Canadian','CA','+1','CAD','Canadian dollar','$',1),
	 (39,'Cape Verde','Cape Verdian','CV','+238','','','',1),
	 (40,'Cayman Islands','Caymanian','KY','+1345','KYD','Cayman Islands dollar','$',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (41,'Central African Republic','Central African','CF','+236','XAF','Central African CFA franc','Fr',1),
	 (42,'Chad','Chadian','TD','+235','XAF','Central African CFA franc','Fr',1),
	 (43,'Chile','Chilean','CL','+56','CLP','Chilean peso','$',1),
	 (44,'China','Chinese','CN','+86','CNY','Chinese yuan','¥',1),
	 (45,'Christmas Island','Christmas Island','CX','+61','AUD','Australian dollar','$',1),
	 (46,'Cocos (Keeling) Islands','Cocos Islander','CC','+61','AUD','Australian dollar','$',1),
	 (47,'Colombia','Colombian','CO','+57','COP','Colombian peso','$',1),
	 (48,'Comoros','Comoran','KM','+269','KMF','Comorian franc','Fr',1),
	 (49,'Republic Of The Congo','Congolese','CG','+242','','','',1),
	 (50,'Democratic Republic Of The Congo','Congolese','CD','+243','','','',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (51,'Cook Islands','Cook Islander','CK','+682','NZD','New Zealand dollar','$',1),
	 (52,'Costa Rica','Costa Rican','CR','+506','CRC','Costa Rican colón','₡',1),
	 (53,'Cote D''Ivoire (Ivory Coast)','Ivorian','CI','+225','','','',1),
	 (54,'Croatia (Hrvatska)','Croatian','HR','+385','','','',1),
	 (55,'Cuba','Cuban','CU','+53','CUC','Cuban convertible peso','$',1),
	 (56,'Cyprus','Cypriot','CY','+357','EUR','Euro','€',1),
	 (57,'Czech Republic','Czech','CZ','+420','CZK','Czech koruna','Kč',1),
	 (58,'Denmark','Danish','DK','+45','DKK','Danish krone','kr',1),
	 (59,'Djibouti','Djibouti','DJ','+253','DJF','Djiboutian franc','Fr',1),
	 (60,'Dominica','Dominican','DM','+1767','XCD','East Caribbean dollar','$',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (61,'Dominican Republic','Dominican','DO','+1809','DOP','Dominican peso','$',1),
	 (62,'East Timor','Zimbabwean','TP','+670','','','',1),
	 (63,'Ecuador','Ecuadorean','EC','+593','USD','United States dollar','$',1),
	 (64,'Egypt','Egyptian','EG','+20','EGP','Egyptian pound','£',1),
	 (65,'El Salvador','Salvadoran','SV','+503','USD','United States dollar','$',1),
	 (66,'Equatorial Guinea','Equatorial Guinean','GQ','+240','XAF','Central African CFA franc','Fr',1),
	 (67,'Eritrea','Eritrean','ER','+291','ERN','Eritrean nakfa','Nfk',1),
	 (68,'Estonia','Estonian','EE','+372','EUR','Euro','€',1),
	 (69,'Ethiopia','Ethiopian','ET','+251','ETB','Ethiopian birr','Br',1),
	 (70,'External Territories of Australia','Zimbabwean','XA','+672','','','',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (71,'Falkland Islands','Falkland Islander','FK','+500','','','',1),
	 (72,'Faroe Islands','Faroese','FO','+298','DKK','Danish krone','kr',1),
	 (73,'Fiji Islands','Fijian','FJ','+679','','','',1),
	 (74,'Finland','Finnish','FI','+358','EUR','Euro','€',1),
	 (75,'France','French','FR','+33','EUR','Euro','€',1),
	 (76,'French Guiana','','GF','+594','','','',1),
	 (77,'French Polynesia','French Polynesian','PF','+689','XPF','CFP franc','Fr',1),
	 (78,'French Southern Territories','French','TF','+262','EUR','Euro','€',1),
	 (79,'Gabon','Gabonese','GA','+241','XAF','Central African CFA franc','Fr',1),
	 (80,'Gambia The','Gambian','GM','+220','','','',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (81,'Georgia','Georgian','GE','+995','GEL','Georgian Lari','ლ',1),
	 (82,'Germany','German','DE','+49','EUR','Euro','€',1),
	 (83,'Ghana','Ghanaian','GH','+233','GHS','Ghanaian cedi','₵',1),
	 (84,'Gibraltar','Gibraltar','GI','+350','GIP','Gibraltar pound','£',1),
	 (85,'Greece','Greek','GR','+30','EUR','Euro','€',1),
	 (86,'Greenland','Greenlandic','GL','+299','DKK','Danish krone','kr',1),
	 (87,'Grenada','Grenadian','GD','+1473','XCD','East Caribbean dollar','$',1),
	 (88,'Guadeloupe','Guadeloupian','GP','+590','EUR','Euro','€',1),
	 (89,'Guam','Guamanian','GU','+1671','USD','United States dollar','$',1),
	 (90,'Guatemala','Guatemalan','GT','+502','GTQ','Guatemalan quetzal','Q',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (91,'Guernsey and Alderney','Zimbabwean','XU','+44-1481','','','',1),
	 (92,'Guinea','Guinean','GN','+224','GNF','Guinean franc','Fr',1),
	 (93,'Guinea-Bissau','Guinea-Bissauan','GW','+245','XOF','West African CFA franc','Fr',1),
	 (94,'Guyana','Guyanese','GY','+592','GYD','Guyanese dollar','$',1),
	 (95,'Haiti','Haitian','HT','+509','HTG','Haitian gourde','G',1),
	 (96,'Heard and McDonald Islands','Heard and McDonald Islander','HM','+0','','','',1),
	 (97,'Honduras','Honduran','HN','+504','HNL','Honduran lempira','L',1),
	 (98,'Hong Kong S.A.R.','Chinese','HK','+852','','','',1),
	 (99,'Hungary','Hungarian','HU','+36','HUF','Hungarian forint','Ft',1),
	 (100,'Iceland','Icelander','IS','+354','ISK','Icelandic króna','kr',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (101,'India','Indian','IN','+91','INR','Indian rupee','₹',1),
	 (102,'Indonesia','Indonesian','ID','+62','IDR','Indonesian rupiah','Rp',1),
	 (103,'Iran','Iranian','IR','+98','IRR','Iranian rial','﷼',1),
	 (104,'Iraq','Iraqi','IQ','+964','IQD','Iraqi dinar','ع.د',1),
	 (105,'Ireland','Irish','IE','+353','EUR','Euro','€',1),
	 (106,'Israel','Israeli','IL','+972','ILS','Israeli new shekel','₪',1),
	 (107,'Italy','Italian','IT','+39','EUR','Euro','€',1),
	 (108,'Jamaica','Jamaican','JM','+1876','JMD','Jamaican dollar','$',1),
	 (109,'Japan','Japanese','JP','+81','JPY','Japanese yen','¥',1),
	 (110,'Jersey','Zimbabwean','XJ','+44','GBP','British pound','£',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (111,'Jordan','Jordanian','JO','+962','JOD','Jordanian dinar','د.ا',1),
	 (112,'Kazakhstan','Kazakhstani','KZ','+7','KZT','Kazakhstani tenge','',1),
	 (113,'Kenya','Kenyan','KE','+254','KES','Kenyan shilling','Sh',1),
	 (114,'Kiribati','I-Kiribati','KI','+686','AUD','Australian dollar','$',1),
	 (115,'Korea North','North Korean','KP','+850','','','',1),
	 (116,'South Korean','South Korean','KR','+82','','','',1),
	 (117,'Kuwait','Kuwaiti','KW','+965','KWD','Kuwaiti dinar','د.ك',1),
	 (118,'Kyrgyzstan','Kirghiz','KG','+996','KGS','Kyrgyzstani som','с',1),
	 (119,'Laos','Laotian','LA','+856','','','',1),
	 (120,'Latvia','Latvian','LV','+371','EUR','Euro','€',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (121,'Lebanon','Lebanese','LB','+961','LBP','Lebanese pound','ل.ل',1),
	 (122,'Lesotho','Mosotho','LS','+266','LSL','Lesotho loti','L',1),
	 (123,'Liberia','Liberian','LR','+231','LRD','Liberian dollar','$',1),
	 (124,'Libya','Libyan','LY','+218','LYD','Libyan dinar','ل.د',1),
	 (125,'Liechtenstein','Liechtensteiner','LI','+423','CHF','Swiss franc','Fr',1),
	 (126,'Lithuania','Lithuanian','LT','+370','EUR','Euro','€',1),
	 (127,'Luxembourg','Luxembourger','LU','+352','EUR','Euro','€',1),
	 (128,'Macau S.A.R.','Chinese','MO','+853','','','',1),
	 (129,'Macedonia','Macedonian','MK','+389','MKD','Macedonian denar','ден',1),
	 (130,'Madagascar','Malagasy','MG','+261','MGA','Malagasy ariary','Ar',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (131,'Malawi','Malawian','MW','+265','MWK','Malawian kwacha','MK',1),
	 (132,'Malaysia','Malaysian','MY','+60','MYR','Malaysian ringgit','RM',1),
	 (133,'Maldives','Maldivan','MV','+960','MVR','Maldivian rufiyaa','.ރ',1),
	 (134,'Mali','Malian','ML','+223','XOF','West African CFA franc','Fr',1),
	 (135,'Malta','Maltese','MT','+356','EUR','Euro','€',1),
	 (136,'Man (Isle of)','Zimbabwean','XM','+44','','','',1),
	 (137,'Marshall Islands','Marshallese','MH','+692','USD','United States dollar','$',1),
	 (138,'Martinique','French','MQ','+596','EUR','Euro','€',1),
	 (139,'Mauritania','Mauritanian','MR','+222','MRO','Mauritanian ouguiya','UM',1),
	 (140,'Mauritius','Mauritian','MU','+230','MUR','Mauritian rupee','₨',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (141,'Mayotte','French','YT','+262','EUR','Euro','€',1),
	 (142,'Mexico','Mexican','MX','+52','MXN','Mexican peso','$',1),
	 (143,'Micronesia','Micronesian','FM','+691','','[D]','$',1),
	 (144,'Moldova','Moldovan','MD','+373','MDL','Moldovan leu','L',1),
	 (145,'Monaco','Monegasque','MC','+377','EUR','Euro','€',1),
	 (146,'Mongolia','Mongolian','MN','+976','MNT','Mongolian tögrög','₮',1),
	 (147,'Montserrat','Montserratian','MS','+1664','XCD','East Caribbean dollar','$',1),
	 (148,'Morocco','Moroccan','MA','+212','MAD','Moroccan dirham','د.م.',1),
	 (149,'Mozambique','Mozambican','MZ','+258','MZN','Mozambican metical','MT',1),
	 (150,'Myanmar','Burmese','MM','+95','MMK','Burmese kyat','Ks',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (151,'Namibia','Namibian','NA','+264','NAD','Namibian dollar','$',1),
	 (152,'Nauru','Nauruan','NR','+674','AUD','Australian dollar','$',1),
	 (153,'Nepal','Nepalese','NP','+977','NPR','Nepalese rupee','₨',1),
	 (154,'Netherlands Antilles','Zimbabwean','AN','+599','','','',1),
	 (155,'Netherlands The','Dutch','NL','+31','','','',1),
	 (156,'New Caledonia','New Caledonian','NC','+687','XPF','CFP franc','Fr',1),
	 (157,'New Zealand','New Zealander','NZ','+64','NZD','New Zealand dollar','$',1),
	 (158,'Nicaragua','Nicaraguan','NI','+505','NIO','Nicaraguan córdoba','C$',1),
	 (159,'Niger','Nigerien','NE','+227','XOF','West African CFA franc','Fr',1),
	 (160,'Nigeria','Nigerian','NG','+234','NGN','Nigerian naira','₦',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (161,'Niue','Niuean','NU','+683','NZD','New Zealand dollar','$',1),
	 (162,'Norfolk Island','Norfolk Islander','NF','+672','AUD','Australian dollar','$',1),
	 (163,'Northern Mariana Islands','American','MP','+1670','USD','United States dollar','$',1),
	 (164,'Norway','Norwegian','NO','+47','NOK','Norwegian krone','kr',1),
	 (165,'Oman','Omani','OM','+968','OMR','Omani rial','ر.ع.',1),
	 (166,'Pakistan','Pakistani','PK','+92','PKR','Pakistani rupee','₨',1),
	 (167,'Palau','Palauan','PW','+680','(none)','[E]','$',1),
	 (168,'Palestinian Territory Occupied','Palestinian','PS','+970','','','',1),
	 (169,'Panama','Panamanian','PA','+507','PAB','Panamanian balboa','B/.',1),
	 (170,'Papua new Guinea','Papua New Guinean','PG','+675','PGK','Papua New Guinean kina','K',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (171,'Paraguay','Paraguayan','PY','+595','PYG','Paraguayan guaraní','₲',1),
	 (172,'Peru','Peruvian','PE','+51','PEN','Peruvian sol','S/.',1),
	 (173,'Philippines','Filipino','PH','+63','PHP','Philippine peso','₱',1),
	 (174,'Pitcairn Island','Pitcairn Islander','PN','+64','','','',1),
	 (175,'Poland','Polish','PL','+48','PLN','Polish złoty','zł',1),
	 (176,'Portugal','Portuguese','PT','+351','EUR','Euro','€',1),
	 (177,'Puerto Rico','Puerto Rican','PR','+1787','USD','United States dollar','$',1),
	 (178,'Qatar','Qatari','QA','+974','QAR','Qatari riyal','ر.ق',1),
	 (179,'Reunion','French','RE','+262','','','',1),
	 (180,'Romania','Romanian','RO','+40','RON','Romanian leu','lei',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (181,'Russia','Russian','RU','+7','','','',1),
	 (182,'Rwanda','Rwandan','RW','+250','RWF','Rwandan franc','Fr',1),
	 (183,'Saint Helena','Saint Helenian','SH','+290','SHP','Saint Helena pound','£',1),
	 (184,'Saint Kitts And Nevis','Kittian and Nevisian','KN','+1869','XCD','East Caribbean dollar','$',1),
	 (185,'Saint Lucia','Saint Lucian','LC','+1758','XCD','East Caribbean dollar','$',1),
	 (186,'Saint Pierre and Miquelon','French','PM','+508','EUR','Euro','€',1),
	 (187,'Saint Vincent And The Grenadines','Saint Vincentian','VC','+1784','XCD','East Caribbean dollar','$',1),
	 (188,'Samoa','Samoan','WS','+685','WST','Samoan tālā','T',1),
	 (189,'San Marino','Sammarinese','SM','+378','EUR','Euro','€',1),
	 (190,'Sao Tome and Principe','Sao Tomean','ST','+239','STD','São Tomé and Príncipe dobra','Db',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (191,'Saudi Arabia','Saudi Arabian','SA','+966','SAR','Saudi riyal','ر.س',1),
	 (192,'Senegal','Senegalese','SN','+221','XOF','West African CFA franc','Fr',1),
	 (193,'Serbia','Serbian','RS','+381','RSD','Serbian dinar','дин.',1),
	 (194,'Seychelles','Seychellois','SC','+248','SCR','Seychellois rupee','₨',1),
	 (195,'Sierra Leone','Sierra Leonean','SL','+232','SLL','Sierra Leonean leone','Le',1),
	 (196,'Singapore','Singaporean','SG','+65','BND','Brunei dollar','$',1),
	 (197,'Slovakia','Slovak','SK','+421','EUR','Euro','€',1),
	 (198,'Slovenia','Slovene','SI','+386','EUR','Euro','€',1),
	 (199,'Smaller Territories of the UK','Zimbabwean','XG','+44','','','',1),
	 (200,'Solomon Islands','Solomon Islander','SB','+677','SBD','Solomon Islands dollar','$',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (201,'Somalia','Somali','SO','+252','SOS','Somali shilling','Sh',1),
	 (202,'South Africa','South African','ZA','+27','ZAR','South African rand','R',1),
	 (203,'South Georgia','South Georgia and the South Sandwich Islander','GS','+500','GBP','British pound','£',1),
	 (204,'South Sudan','South Sudanese','SS','+211','SSP','South Sudanese pound','£',1),
	 (205,'Spain','Spanish','ES','+34','EUR','Euro','€',1),
	 (206,'Sri Lanka','Sri Lankan','LK','+94','LKR','Sri Lankan rupee','Rs',1),
	 (207,'Sudan','Sudanese','SD','+249','SDG','Sudanese pound','ج.س.',1),
	 (208,'Suriname','Surinamer','SR','+597','SRD','Surinamese dollar','$',1),
	 (209,'Svalbard And Jan Mayen Islands','Norwegian','SJ','+47','','','',1),
	 (210,'Swaziland','Swazi','SZ','+268','SZL','Swazi lilangeni','L',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (211,'Sweden','Swedish','SE','+46','SEK','Swedish krona','kr',1),
	 (212,'Switzerland','Swiss','CH','+41','CHF','Swiss franc','Fr',1),
	 (213,'Syria','Syrian','SY','+963','SYP','Syrian pound','£',1),
	 (214,'Taiwan','Taiwanese','TW','+886','TWD','New Taiwan dollar','$',1),
	 (215,'Tajikistan','Tadzhik','TJ','+992','TJS','Tajikistani somoni','ЅМ',1),
	 (216,'Tanzania','Tanzanian','TZ','+255','TZS','Tanzanian shilling','Sh',1),
	 (217,'Thailand','Thai','TH','+66','THB','Thai baht','฿',1),
	 (218,'Togo','Togolese','TG','+228','XOF','West African CFA franc','Fr',1),
	 (219,'Tokelau','Tokelauan','TK','+690','NZD','New Zealand dollar','$',1),
	 (220,'Tonga','Tongan','TO','+676','TOP','Tongan paʻanga','T$',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (221,'Trinidad And Tobago','Trinidadian','TT','+1868','TTD','Trinidad and Tobago dollar','$',1),
	 (222,'Tunisia','Tunisian','TN','+216','TND','Tunisian dinar','د.ت',1),
	 (223,'Turkey','Turkish','TR','+90','TRY','Turkish lira','',1),
	 (224,'Turkmenistan','Turkmen','TM','+993','TMT','Turkmenistan manat','m',1),
	 (225,'Turks And Caicos Islands','Turks and Caicos Islander','TC','+1649','USD','United States dollar','$',1),
	 (226,'Tuvalu','Tuvaluan','TV','+688','AUD','Australian dollar','$',1),
	 (227,'Uganda','Ugandan','UG','+256','UGX','Ugandan shilling','Sh',1),
	 (228,'Ukraine','Ukrainian','UA','+380','UAH','Ukrainian hryvnia','₴',1),
	 (229,'United Arab Emirates','Emirati','AE','+971','AED','United Arab Emirates dirham','د.إ',1),
	 (230,'United Kingdom','British','GB','+44','GBP','British pound','£',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (231,'United States','American','US','+1','','','',1),
	 (232,'United States Minor Outlying Islands','American','UM','','USD','United States Dollar','$',1),
	 (233,'Uruguay','Uruguayan','UY','+598','UYU','Uruguayan peso','$',1),
	 (234,'Uzbekistan','Uzbekistani','UZ','+998','UZS','Uzbekistani so''m','',1),
	 (235,'Vanuatu','Ni-Vanuatu','VU','+678','VUV','Vanuatu vatu','Vt',1),
	 (236,'Vatican City State (Holy See)','','VA','+379','','','',1),
	 (237,'Venezuela','Venezuelan','VE','+58','VEF','Venezuelan bolívar','Bs F',1),
	 (238,'Vietnam','Vietnamese','VN','84','VND','Vietnamese đồng','₫',1),
	 (239,'Virgin Islands (British)','Virgin Islander','VG','+1284','','[D]','$',1),
	 (240,'Virgin Islands (US)','Virgin Islander','VI','+340','','','',1);
INSERT INTO tbl_countries (id,name,nationality,sortname,calling_code,currency_code,currency_name,currency_symbol,status) VALUES
	 (241,'Wallis And Futuna Islands','Wallis and Futuna Islander','WF','+681','','','',1),
	 (242,'Western Sahara','Sahrawi','EH','+212','MAD','Moroccan dirham','د.م.',1),
	 (243,'Yemen','Yemeni','YE','+967','YER','Yemeni rial','﷼',1),
	 (244,'Yugoslavia','Zimbabwean','YU','+38','','','',1),
	 (245,'Zambia','Zambian','ZM','+260','ZMW','Zambian kwacha','ZK',1),
	 (246,'Zimbabwe','Zimbabwean','ZW','+263','BWP','Botswana pula','P',1);