const checkValidatorRules = {
    userSignUp: {
        language: 'required|in:English,Gujarati',
        en_full_name: 'required',
        guj_full_name: 'required',
        email: 'required|email',
        country_code: 'required',
        phone_no: 'required',
        password: 'required',
        role: 'required|in:0',
        device_type: 'required|in:W,A,I',
        device_token: 'required',
        uuid: 'required',
        os_version: 'required',
        device_model: 'required',
        app_version: 'required',
    },
    vendorSignUp: {
        language: 'required|in:English,Gujarati',
        en_full_name: 'required',
        guj_full_name: 'required',
        email: 'required|email',
        country_code: 'required',
        phone_no: 'required',
        dob: 'required',
        password: 'required',
        profile_image: 'required',
        role: 'required|in:1',
        device_type: 'required|in:W,A,I',
        device_token: 'required',
        uuid: 'required',
        os_version: 'required',
        device_model: 'required',
        app_version: 'required',
        market_place_id: 'required',
        category_id: 'required',
        en_store_name: 'required',
        guj_store_name: 'required',
        whatsapp_number: 'required',
        gstno: '',
        address_line_1: 'required',
        address_line_2: 'required',
        state: 'required',
        city: 'required',
        pincode: 'required',
        landmark: '',
    },
    serviceProviderSignUp: {
        language: 'required|in:English,Gujarati',
        en_full_name: 'required',
        guj_full_name: 'required',
        email: 'required|email',
        country_code: 'required',
        phone_no: 'required',
        dob: 'required',
        password: 'required',
        role: 'required|in:2',
        profile_image: 'required',
        device_type: 'required|in:W,A,I',
        device_token: 'required',
        uuid: 'required',
        os_version: 'required',
        device_model: 'required',
        app_version: 'required',
        market_place_id: 'required',
        category_id: 'required',
        en_name: 'required',
        guj_name: 'required',
        whatsapp_number: 'required',
        service_profile_image: 'required',
        en_work_details: 'required',
        guj_work_details: 'required',
        address_line_1: 'required',
        address_line_2: 'required',
        state: 'required',
        city: 'required',
        pincode: 'required',
        work_image: 'required',
        landmark: '',
        latitude: '',
        longitude: '',
    },
    login: {
        email: '',
        phone_no: '',
        country_code: '',
        password: 'required',
        device_type: 'required|in:W,A,I',
        device_token: 'required',
        uuid: 'required',
        os_version: 'required',
        device_model: 'required',
        app_version: 'required',
    },
    sendOtp: {
        functionality: 'required|in:forgotPassword,updateEmail,updatePhoneNumber,signUp',
        email: 'required|email',
    },
    verifyOtp: {
        functionality: 'required|in:forgotPassword,updateEmail,updatePhoneNumber,updateProfile,signUp',
        email: 'required|email',
        otp: 'required',
    },
    newPassword: {
        email: 'required|email',
        password: 'required',
    },
    changePassword: {
        old_password: 'required',
        new_password: 'required',
    },
    updateProfile: {
        en_full_name: 'required',
        guj_full_name: 'required',
        email: 'required|email',
        country_code: 'required',
        phone_no: 'required',
        profile_image: 'required',
        language: 'required|in:English,Gujarati',
    },
    enableDisableNotification: {
        is_notification: 'required|in:0,1',
    },
    getStoreCategory: {
        role: 'required|in:0,1,2',
    },
    getProductCategory: {
        store_category_id: '',
        role: 'required|in:0,1,2',
    },
    getProductSubCategory: {
        store_category_id: '',
        category_id: 'required',
    },
    addProduct: {
        user_id: 'required',
        name: 'required',
        used_space: 'required',
        category_id: 'required',
        subcategory_id: 'required',
        store_id: 'required',
        price: 'required',
        images: 'required',
        product_code: '',
        discount: '',
        discount_type: '',
        brand: '',
        gender: '',
        color: '',
        size: '',
        shape: '',
        material: '',
        pattern: '',
        design: '',
        type: '',
        sustainable: '',
        warranty: '',
        guarantee: '',
        quantity: '',
        quality: '',
        service: '',
        replacement: '',
        resale: '',
        details: '',
    },
    deleteProduct: {
        product_id: 'required',
    },
    getProductDetails: {
        product_id: 'required',
    },
    updateProduct: {
        user_id: 'required',
        product_id: 'required',
        name: 'required',
        used_space: 'required',
        category_id: 'required',
        subcategory_id: 'required',
        store_id: 'required',
        price: 'required',
        images: 'required',
        product_code: '',
        discount: '',
        discount_type: '',
        brand: '',
        gender: '',
        color: '',
        size: '',
        shape: '',
        material: '',
        pattern: '',
        design: '',
        type: '',
        sustainable: '',
        warranty: '',
        guarantee: '',
        quantity: '',
        quality: '',
        service: '',
        replacement: '',
        resale: '',
        details: '',
    },
    getStoreList: {
        page: 'required',
        record_count: 'required',
    },
    getStoreDetails: {
        store_id: 'required',
    },
    getStoreProductList: {
        store_id: 'required',
        page: 'required',
        record_count: 'required',
        search_text: '',
    },
    addStoreDetails: {
        market_place_id: 'required',
        category_id: 'required',
        en_store_name: 'required',
        guj_store_name: 'required',
        whatsapp_number: 'required',
        gstno: '',
        address_line_1: 'required',
        address_line_2: 'required',
        state: 'required',
        city: 'required',
        pincode: 'required',
        landmark: '',
    },
    updateStoreDetails: {
        store_id: 'required',
        market_place_id: 'required',
        category_id: 'required',
        en_store_name: 'required',
        guj_store_name: 'required',
        whatsapp_number: 'required',
        gstno: '',
        address_line_1: 'required',
        address_line_2: 'required',
        state: 'required',
        city: 'required',
        pincode: 'required',
        landmark: '',
    },
    deleteStoreDetails: {
        store_id: 'required',
    },
    getMostRatedProductList: {
        page: 'required',
        record_count: 'required',
        store_id: 'required',
    },
    getMostTradingProductList: {
        page: 'required',
        record_count: 'required',
        store_id: 'required',
    },
    updateProductStatus: {
        status: 'required',
        product_id: 'required',
    },
    getS3BucketUrl: {
        fileName: 'required',
        filetype: 'required',
        folder_name: 'required',
    },
    getDashboardCount: {
        store_id: 'required',
    },
    getSaveProductList: {
        page: 'required',
        record_count: 'required',
        store_id: 'required',
    },
    getSaveProductUserList: {
        page: 'required',
        record_count: 'required',
    },
    getLikeProductList: {
        page: 'required',
        record_count: 'required',
        //store_id:'required',
    },
    getVenodrLikeProductList: {
        page: 'required',
        record_count: 'required',
        store_id: 'required',
    },
    getSubscriptionPlans: {
        type: 'required|in:1,2',
    },
    getNotificationList: {
        user_id: 'required',
    },
    getServices: {
        user_id: 'required',
    },
    addService: {
        user_id: 'required',
        profile_image: 'required',
        en_work_details: 'required',
        guj_work_details: 'required',
        address_line_1: 'required',
        address_line_2: 'required',
        state: 'required',
        city: 'required',
        pincode: 'required',
        market_place_id: 'required',
        category_id: 'required',
        en_name: 'required',
        guj_name: 'required',
        work_image: 'required',
        whatsapp_number: 'required',
        landmark: '',
        latitude: '',
        longitude: '',
    },
    updateService: {
        service_id: 'required',
        profile_image: 'required',
        en_work_details: 'required',
        guj_work_details: 'required',
        address_line_1: 'required',
        address_line_2: 'required',
        state: 'required',
        city: 'required',
        pincode: 'required',
        market_place_id: 'required',
        category_id: 'required',
        en_name: 'required',
        guj_name: 'required',
        work_image: 'required',
        whatsapp_number: 'required',
        landmark: '',
        latitude: '',
        longitude: '',
    },
    deleteService: {
        service_id: 'required',
    },
    getProductList: {
        page: 'required',
        record_count: 'required',
        search_text: '',
    },
    likeUnlikeProduct: {
        product_id: 'required',
        store_id: 'required',
        is_like: 'required|in:0,1',
    },
    saveUnsaveProduct: {
        product_id: 'required',
        store_id: 'required',
        is_save: 'required|in:0,1',
    },
    followUnfollow: {
        follower_id: 'required',
        is_follow: 'required|in:0,1',
    },
    addReview: {
        product_id: 'required',
        rating: 'required|in:1,2,3,4,5',
        role: 'required|in:0,1,2',
        review: 'required',
    },
    editReview: {
        review_id: 'required',
        rating: 'required|in:1,2,3,4,5',
        review: 'required',
    },
    editReview: {
        review_id: 'required',
    },
    getReviewList: {
        role: 'required|in:0,1,2',
        page: 'required',
        record_count: 'required',
        product_id: 'required',
    },
    getServiceProviderDetails: {
        service_provider_id: 'required',
    },
    getSimilarProducts: {
        page: 'required',
        record_count: 'required',
        category_id: 'required',
        product_id: 'required',
    },
    homePage: {
        market_place_id: 'required',
        category_id: 'required',
    },
    getAllProducts: {
        page: 'required',
        record_count: 'required',
        market_place_id: 'required',
        category_id: '',
        is_product: 'required|in:1,2,3',
        search_text: '',
        price_range_start: '',
        price_range_end: '',
        subcategory_id: '',
    },
    getUserStoreList: {
        search_text: '',
    },
    getUserServiceProviderList: {
        search_text: '',
    },
    getAllUserStoreList: {
        page: 'required',
        record_count: 'required',
        category_id: 'required',
    },
    getAllUserServiceProviderList: {
        page: 'required',
        record_count: 'required',
        category_id: 'required',
    },
    getUserStoreProductList: {
        store_id: 'required',
        page: 'required',
        record_count: 'required',
        search_text: '',
    },
    chatNotification: {
        notification_data: 'required',
    },
    adBannerList: {
        market_place_id: 'required',
        page_name: 'required',
        store_category_id: '',
    },
    sendOtpEditProfile: {
        phone_no: '',
        email: '',
    },
    addFeeback: {
        app_in_like: 'required',
        rating: 'required|in:1,2,3,4,5',
        comment: '',
    },
    addContactUs: {
        en_name: 'required',
        guj_name: 'required',
        email: 'required',
        phone: 'required',
        comment: 'required',
    },
    addImpressionCount: {
        ads_id: 'required',
    },
    getContactDetails: {

    },
    checkAppVersion: {
        device_type: 'required',
        version: 'required',
        //role: 'required',
    },
    feedbackReasonsList: {
        role: 'required|in:0,1,2',
    },
    getStoreCategorySubcategory: {
        store_id: 'required',
    },
    getProductCategorySubcategory: {
        store_id: 'required',
    },
};

export default checkValidatorRules;
